### PR TITLE
Add issues basic line chart with dates

### PR DESCRIPTION
**Pull request by MarkDBlackwell**
Includes a basic line chart of the user's mood.

Removed the factories, increased the readability, decreased the abstraction, yet kept it DRY. I hope this is better for you!

shot

### CODE REVIEW

**Comment by akshatpradhan** [comment]
Ah, interesting
1. Can you make it so that it only shows 29 Mar, 30 Mar and not show time?
2. Can you remove the horizontal grid lines? 
3. Can you make it so that it only shows 0 to 5 and not 6? 
4. Can you change the word for "happiness_level" to "Happiness level", this also for anxiety and irritation

**Comment by akshatpradhan** [comment]
@MarkDBlackwell Also, can you send another pull request where its a pie chart? I know that sounds strange, but I'm curious how that would look. Perhaps make it so that only the past month is charted.

**Comment by MarkDBlackwell** [comment]
Q 1. Can you make it so that it only shows 29 Mar, 30 Mar and not show time?

A 1: [This](http://api.highcharts.com/highcharts#xAxis.minTickInterval) says we can prevent anything smaller than a day.

Q 2. Can you remove the horizontal grid lines?

A 2: [This](http://api.highcharts.com/highcharts#yAxis.gridLineWidth) says we can hide the lines by using width 0. That's the best way.

Q 3. Can you make it so that it only shows 0 to 5 and not 6?

A 3: [This](http://api.highcharts.com/highcharts#yAxis.max) says we can max and min the y axis to do just that.

Q 4. Can you change the word for "happiness_level" to "Happiness level", this also for anxiety and irritation

A 4: Easy to do.

We can also try more things like this in JSFiddles on the the High Charts site. Whatever works there seems to me highly likely to work in Spoutlets' Ruby code with our gem, lazy_high_charts.

**Comment by MarkDBlackwell** [comment]
@akshatpradhan, I'm assuming you mean: show for the most recent 30 days the totals of all the happiness ratings, all the anxiety ratings, and all the irritation ratings.

I'm assuming you want totals [1, 1, 1] to look identical to [100, 100, 100]. This is what HighCharts does.

BTW, the pathological case of [0,0,0] might be common for new users. High Charts seems to work well when [this](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/type-bar/) is changed to a pie chart and we remove all the 0 totals. An empty array shows as an empty chart.

**Comment by MarkDBlackwell** [comment]
All comments are addressed in new pull request #76.

**Comment by MarkDBlackwell** [comment]
Hi, Akshat,
I sent a new pull request for it.

With warm regards,
Mark D. Blackwell

**Pull request closed without merging**
