### PR TITLE
Therapists omniauth

### PR DESCRIPTION
**Pull request by adamico**
I had a great time with this pull request :)
Makes me wanna migrate to mongoid. I had always been scared of cutting the umbilical cord with sql, but now I'm confident enough with Rails to do that for my projects. Thanks, akshat :+1:

### CODE REVIEW

**Comment by akshatpradhan** [comment]
## Change Description - :worried: 

### What does this change do?

This changes the authentication mechanisms for both Patients and Therapists. Therapists will be forced to login with a LinkedIn account. This adds transparency showing therapist's qualification to the Patient. Moreover, patients will now be forced to create accounts with their email/password. This allows for improved anonymity for the Patients.
- [x] adds environment variables for omniauth credentials https://github.com/adamico/spoutlets/commit/f009e33a053dae8d1fa897204ff7d347a1c2f9b9
- [x] configures column names for the Therapist table for omniauth settings https://github.com/adamico/spoutlets/commit/0909e38b0b976ea5785e1b554854332cb8a81bb8
- [x] removes unused test cases https://github.com/adamico/spoutlets/commit/d553fc8ec3beb3fefea370a7d990e65e2414f382
- [x] adds devise and removes omniauth
- [x] configures email and views

### What testing has been done?

This has been QA'd locally and appropriate tests have been run. However, this is not nearly enough testing to conclude no bugs or problems. We've deployed this testing on production since users < 50. We will have to spot QA and spot monitor the site for _1 month_ to ensure the safest, user-friendly experience.

## Risk Assessment

### What are the risks?

The risks are highly increased. It was safer to use Facebook authentication because we didn't have to store passwords. However, people had a high adversity to anything touching their personal Facebook information, and thus would not register. To make this site more accessible, we have to allow people to register with their email and password. This is our business justification.

### Is there a business impact?

There is a business impact. People will be unable to login for the next couple of weeks as we continuously QA the bugs. Since are users are < 50, we won't bothering them with an annoying email, and we choose to QA in production. This allows us to step through the bugs slowly and mitigate any problems before reaching out to users for feedback again. 

## Future Assessment

We will allow people to delete their accounts entirely.

**Comment by akshatpradhan** [comment]
@adamico I'm glad you're having fun as well!

**Comment by akshatpradhan** [comment]
@adamico Would you be able to peer review my Change Request and add any additional comments that you think are important? https://github.com/akshatpradhan/spoutlets/pull/147#issuecomment-25461010 @billiedemott

**Comment by adamico** [comment]
I made a long commit message to this commit c6e7ef6d15dad8d4f932b2a0568f5f6440bfbc43 but I forgot to add it to the pull request description. I would change the phrase "Moreover, patients will not be forced to create accounts with their email/password" to "Moreover, patients will **now** be forced to create accounts with their email/password".

Concerning the user migration to devise with email/password, I added a rake task for mass sending password reset to users not having set a password yet (i.e. all users previously registered and logging in with Facebook), so you can launch the task in production when you think you are ready for the migration.

I agree more tests are needed. I think you should start using the github issues system and then I'll help fixing them with pull requests.

**Pull request merged**
