### PR TITLE
Add session fixation countermeasure

### PR DESCRIPTION
**Pull request by MarkDBlackwell**

### CODE REVIEW

**Comment by akshatpradhan** [comment]
Do you think `reset_session` is already part of the `omniauth` gem? If so, we don't need to explicitly define it here, right?

**Comment by MarkDBlackwell** [comment]
Good question! But this is not defining it. This is invoking the existing `reset_session` method to make a new session ID during a successful login process. This prevents session fixation attacks as described in sections [2.7](http://guides.rubyonrails.org/security.html#session-fixation) and [2.8](http://guides.rubyonrails.org/security.html#session-fixation-countermeasures) of the Ruby On Rails Security Guide.

Attackers using XSS can set the victim's unlogged-in session cookie on a site to be the same as their own. Thus they are sharing the same session ID and the same session as the victim. Later if they lure the victim to log in, then that session ID is logged in and thus the attacker's computer is logged in too. Then the attacker can perform whatever actions they want as the logged in user. It's a two-step process separated by a considerable time delay.

That kind of attack can be effective unless we change the session ID at each successful login, so that from the moment the victim logs in, the attacker's session ID won't match anymore. This protects the actions we limit to logged in users.

**Comment by akshatpradhan** [comment]
Do you think this should be a bug filed with @DanielKehoe ? `reset_session` seems like something that should be in the RailsApps by default, no?

**Comment by MarkDBlackwell** [comment]
I'll be happy to look into wherever it comes from, and file an issue there.

**Comment by MarkDBlackwell** [comment]
Just now I filed a [pull request](https://github.com/RailsApps/rails3-mongoid-omniauth/pull/24) for RailsApps to enable this security protection functionality.

**Pull request merged**
